name: GBA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download devkitpro
      run: wget https://apt.devkitpro.org/install-devkitpro-pacman
    - name: devkitpro install
      run: chmod +x ./install-devkitpro-pacman && ./install-devkitpro-pacman
    - name: install pkg
      run: pacman -S gba-dev
    - name: add to path
      run: source /etc/profile.d/devkit-env.sh
    - name: configure
      run: arm-none-eabi-cmake . -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build .

