name: GBA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download devkitpro
      run: wget https://apt.devkitpro.org/install-devkitpro-pacman
    - name: chmod
      run: chmod +x ./install-devkitpro-pacman
    - name: devkitpro install
      run: until sudo ./install-devkitpro-pacman; do echo "Retrying"; done
    - name: install pkg
      run: sudo dkp-pacman -S gba-dev --noconfirm
    - name: add to path
      run: source /etc/profile.d/devkit-env.sh
    - name: dependencies
      run: sudo apt-get install libglvnd-dev libxi-dev libxcursor-dev libasound2-dev
    - name: mkdir
      run: mkdir build
    - name: configure
      run: cmake .. -DHOST_SYSTEM_NAME=GBA -DCMAKE_BUILD_TYPE=Release
      working-directory: ./build
    - name: build
      run: cmake --build .
      working-directory: ./build

