name: GBA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download devkitpro
      run: wget https://github.com/devkitPro/buildscripts/archive/refs/tags/devkitARM_r63.tar.gz
    - name: extract
      run: tar -xvf devkitARM_r63.tar.gz
    - name: configure
      run: sed -i 's/=0/=1/g' config.sh.sample; mv config.sh.sample config.sh;
      working-directory: ./buildscripts-devkitARM_r63
    - name: dependencies
      run: sudo apt-get install libglvnd-dev libxi-dev libxcursor-dev libasound2-dev libgmp-dev libmpfr-dev libmpc-dev libfreeimage-dev zlib1g-dev libusb-dev libudev-dev libexpat1-dev
    - name: install pkg
      run: sudo ./build-devkit.sh
      working-directory: ./buildscripts-devkitARM_r63
    - name: add to path
      run: echo "PATH=/opt/devkitpro/tools/bin:$PATH" >> $GITHUB_ENV
    - name: mkdir
      run: mkdir build
    - name: configure
      run: cmake .. -DHOST_SYSTEM_NAME=GBA -DCMAKE_BUILD_TYPE=Release
      working-directory: ./build
    - name: build
      run: cmake --build .
      working-directory: ./build

