name: GBA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download devkitpro
      run: wget https://apt.devkitpro.org/install-devkitpro-pacman
    - name: chmod
      run: chmod +x ./install-devkitpro-pacman
    - name: fix
      run: sed -i 's/apt-get install devkitpro-pacman/until apt-get install devkitpro-pacman; do echo "Retrying"; done/g' install-devkitpro-pacman
    - name: devkitpro install
      run: sudo ./install-devkitpro-pacman
    - name: install pkg
      run: sudo dkp-pacman -S gba-dev --noconfirm
    - name: add to path
      run: source /etc/profile.d/devkit-env.sh
    - name: dependencies
      run: apt-get install libglvnd-dev
    - name: mkdir
      run: mkdir build
    - name: configure
      run: cmake .. -DHOST_SYSTEM_NAME=GBA -DCMAKE_BUILD_TYPE=Release
      working-directory: ./build
    - name: build
      run: cmake --build .
      working-directory: ./build

