name: Ubuntu CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: sync repos
      run: sudo apt-get update
    - name: install dependencies
      run: bash builddeps.sh
    - name: make
      run: make release
