name: Emscripten CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clone emsdk
      run: git clone https://github.com/emscripten-core/emsdk.git
    - name: emsdk install
      run: ./emsdk/emsdk install latest
    - name: emsdk activate
      run: ./emsdk/emsdk activate latest
    - name: emsdk source
      run: source ./emsdk/emsdk_env.sh
    - name: configure
      run: emcmake cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build .

