name: Emscripten CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clone emsdk
      run: git clone https://github.com/emscripten-core/emsdk.git
    - name: emsdk install
      run: ./emsdk/emsdk install latest
    - name: emsdk activate
      run: ./emsdk/emsdk activate latest
    - name: add to path
      run: echo /home/runner/work/tidal2d/tidal2d/emsdk/upstream/emscripten >> $GITHUB_PATH
    - name: mkdir
      run: mkdir build
    - name: configure
      run: cmake .. -DHOST_SYSTEM_NAME=Emscripten -DCMAKE_BUILD_TYPE=Release
      working-directory: ./build
    - name: build
      run: cmake --build .
      working-directory: ./build

